server:
  port: 8084
  servlet:
    context-path: /api
spring:
  application:
    name: payment-control
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
      